# Generated by Django 3.2.14 on 2022-07-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytodo',
            name='description',
            field=models.TextField(default='hi'),
        ),
        migrations.AlterField(
            model_name='mytodo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
