# Generated by Django 3.2.14 on 2022-07-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_auto_20220721_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytodo',
            name='description',
            field=models.TextField(),
        ),
    ]
